// src/components/ExtractRecipeButton.vue
<template>
  <div class="section">
    <textarea placeholder="Paste recipe URL here" v-model="url" class="textarea" />
    <button @click="handleExtractAndUpload" :disabled="isLoading || !url.trim()" class="button">
      {{ isLoading ? 'Extracting...' : 'Extract Recipe' }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { extractRecipe } from '@/lib/fetchRecipe'
import type { Recipe } from '@/types/recipe'
import { ref } from 'vue'

const emit = defineEmits<{
  (e: 'clickedAndChanged', recipe: Recipe): void
}>()

const url = ref('')
const isLoading = ref(false)

const handleExtractAndUpload = async () => {
  isLoading.value = true
  try {
    console.log('Extracting recipe from URL:', url.value)
    const image = await extractRecipe(url.value)

    if (!image) {
      alert('No image found or image is invalid.')
      isLoading.value = false
      return
    }

    emit('clickedAndChanged', image)
    alert('Image processed!')
    url.value = ''
  } catch (error) {
    console.error('Error:', error)
    alert('Failed to extract recipe.')
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
@import url('@/styles/Input.css');
</style>

// src/components/ExtractRecipeButton.tsx
import { useState } from 'react';
import { extractRecipe } from "@/lib/fetchRecipe"; // Make sure this is correctly implemented
import { Recipe } from '@/types/recipe';
import styles from "./Input.module.css"

const AddDishButton = ({ onClickedAndChanged }: { onClickedAndChanged: (recipe: Recipe) => void }) => {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);

  const handleExtractAndUpload = async () => {
    setLoading(true);
    try {
      console.log('Extracting recipe from URL:', url);
      const recipe = await extractRecipe(url);

      if (!recipe) {
        alert('No recipe found or recipe is invalid.');
        setLoading(false);
        return;
      }

      onClickedAndChanged(recipe);
      alert('Dish processed!');
      setUrl('');
    } catch (error) {
      console.error('Error:', error);
      alert('Failed to extract the dish.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.section}>
      <textarea
        placeholder="Paste recipe URL here"
        value={url}
        onChange={(e) => setUrl(e.target.value)}
        className={styles.textarea}
      />
      <button onClick={handleExtractAndUpload} disabled={loading || !url.trim()} className={styles.button}>
        {loading ? 'Extracting...' : 'Extract Recipe'}
      </button>
    </div>
  );
};

export default AddDishButton;
