// src/components/NavBar.vue
<script setup lang="ts">
import { RouterLink, useRouter } from 'vue-router'
import { getRedirectResult, signOut, signInWithPopup, type UserCredential } from 'firebase/auth'
import { GoogleAuthProvider } from 'firebase/auth'
import { useFirebaseAuth, useCurrentUser } from 'vuefire'
import { onMounted, ref } from 'vue'
import profile from '@/logos/profile-user.png'
import burger from '@/logos/menu-burger.svg'

defineProps<{
  search?: boolean
}>()

const auth = useFirebaseAuth()!
const user = useCurrentUser()
const error = ref(null)
const isHamburgerShown = ref(false)
const router = useRouter()

const googleAuthProvider = new GoogleAuthProvider()
function signOutLocal() {
  signOut(auth).catch((reason) => {
    console.error('Failed signinRedirect', reason)
    error.value = reason
  })
}
function signinPopup() {
  error.value = null
  signInWithPopup(auth, googleAuthProvider)
    .catch((reason) => {
      console.error('Failed sign', reason)
      error.value = reason
    })
    .then((user: void | UserCredential) => {
      if (user && user.user.email !== 'kiskovi97@gmail.com') {
        alert('You have no permission to enter this page')
        signOutLocal()
      }
    })
}
onMounted(() => {
  getRedirectResult(auth).catch((reason) => {
    console.error('Failed redirect result', reason)
    error.value = reason
  })
})
const onSearchBlur = (event: FocusEvent) => {
  const input = event.target as HTMLInputElement
  const query = input.value.trim()
  if (query.length > 0) {
    router.push(`/search?search=${encodeURIComponent(query)}`)
  }
}

const onHandleProfileClick = () => {
  if (user.value) {
    signOutLocal()
  } else {
    signinPopup()
  }
}
</script>

<template>
  <div class="main">
    <div class="hamburger">
      <img
        :src="burger"
        alt=""
        width="24"
        height="24"
        @click="isHamburgerShown = !isHamburgerShown"
      />
      <div v-if="isHamburgerShown" class="tabs_hamburger">
        <div><RouterLink to="/desserts">Desserts</RouterLink></div>
        <div><RouterLink to="/dishes">Main dishes</RouterLink></div>
        <div><RouterLink to="/search">All</RouterLink></div>
        <template v-if="user">
          <div><RouterLink to="/upload">Upload</RouterLink></div>
          <div><RouterLink to="/inspection">Inspection</RouterLink></div>
        </template>
      </div>
    </div>
    <div class="title">
      <RouterLink to="/">Husband Material</RouterLink>
    </div>
    <div class="tabs">
      <div><RouterLink to="/desserts">Desserts</RouterLink></div>
      <div><RouterLink to="/dishes">Main dishes</RouterLink></div>
      <div><RouterLink to="/search">All</RouterLink></div>
      <template v-if="user">
        <div><RouterLink to="/upload">Upload</RouterLink></div>
        <div><RouterLink to="/inspection">Inspection</RouterLink></div>
      </template>
    </div>

    <div v-if="search" class="search">
      <input type="text" placeholder="Search..." @blur="onSearchBlur" />
    </div>
    <div class="profile">
      <img
        class="profileImage"
        :src="user?.photoURL || profile"
        alt=""
        width="24"
        height="24"
        @click="onHandleProfileClick"
      />
    </div>
  </div>
</template>

<style scoped>
.main {
  margin-left: 2rem;
  margin-right: 2rem;
  padding: 1rem;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  gap: 2rem;
  line-height: 1.2rem;
}

.title {
  font-style: normal;
  font-weight: 700;
  font-size: 18px;
  color: var(--darkestColor);
  overflow: hidden;
}

.search {
  overflow: hidden;
}

.tabs {
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  align-items: center;
  gap: 2rem;
  flex-grow: 1;
  font-size: 14px;
}

.tabs_hamburger {
  position: absolute;
  top: 4rem;
  left: 2rem;
  width: 10rem;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  background-color: white;
  gap: 2rem;
  font-size: 14px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
  z-index: 1000;
  padding: 1.5rem 1rem;
  border-radius: 0.5rem;
  overflow: hidden;
}

.main a {
  color: var(--darkestColor);
  text-decoration: none;
}

.main a:hover {
  color: var(--mainColor);
}

.hamburger {
  width: 0;
  height: 0;
  overflow: hidden;
}

@media only screen and (max-width: 60em) {
  .tabs {
    gap: 0.5rem;
    justify-content: space-between;
    flex-grow: unset;
  }
  .title {
    max-width: 6rem;
  }
  .main {
    margin-left: 0rem;
    margin-right: 0rem;
    justify-content: start;
    gap: 1rem;
  }

  .profile {
    position: absolute;
    top: 1rem;
    right: 1rem;
  }

  .search {
    width: 0px;
  }
}

@media only screen and (max-width: 40em) {
  .tabs {
    width: 0;
    height: 0;
    overflow: hidden;
  }
  .hamburger {
    width: 24px;
    height: 24px;
    overflow: visible;
  }
}
</style>

// src/components/Navbar.tsx
'use client'

import styles from './Header.module.css';
import Link from "next/link";
import Image from 'next/image';
import { useRouter } from "next/navigation";

import burger from '@/logos/menu-burger.svg'
import profile from '@/logos/profile-user.png'
import { useState } from 'react';
import { signOut, signInWithPopup } from "firebase/auth";
import { auth, googleProvider } from "@/lib/firebase";
import { useAuth } from "./AuthContext";

interface NavbarProps {
  search?: boolean;
}

var Navbar: React.FC<NavbarProps> = ({search}) =>
{
    const { user } = useAuth();
    const [isHamburgerHidden, setHamburgerHidden] = useState(true);
    const router = useRouter();

    const handleGoogleSignOut = async () => {
        try {
        await signOut(auth);
        console.log("User signed out");
        } catch (error) {
        console.error("Google Sign-Out Error:", error);
        alert("YGoogle Sign-In Error");
        }
    };

    const handleGoogleSignIn = async () => {
        try {
        const result = await signInWithPopup(auth, googleProvider);
        const user = result.user;
        if (user.email !== "kiskovi97@gmail.com") {
            alert("You are not authorized to access this page.");
            await signOut(auth);
        }
        } catch (error) {
        console.error("Google Sign-In Error:", error);
        alert("Google Sign-In Error");
        }
    };

    return (
    <div className={styles.main}>
        <div className={styles.hamburger}>
            <Image src={burger.src} alt=""  width={24} height={24} onClick={() => {setHamburgerHidden(!isHamburgerHidden)}}/>
            {
                (isHamburgerHidden) ? 
                <div/> :
                <div className={styles.tabs_hamburger} hidden={isHamburgerHidden}>
                    <div> <Link href="/desserts" >Desserts</Link></div>
                    <div> <Link href="/dishes" >Main dishes</Link></div>
                    <div> <Link href="/all" >All</Link></div>
                    {
                        user && (
                            <>
                                <div> <Link href="/upload" >Upload</Link></div>
                                <div> <Link href="/inspection" >Inspection</Link></div>
                            </>
                        )
                    }
                </div>
            }
        </div>
        <div className={styles.title}>
            <div> <Link href="/">Husband Material</Link></div>
        </div>
        <div className={styles.tabs}>
            <div> <Link href="/desserts" >Desserts</Link></div>
            <div> <Link href="/dishes" >Main dishes</Link></div>
            <div> <Link href="/all" >All</Link></div>
            {
                user && (
                    <>
                        <div> <Link href="/upload" >Upload</Link></div>
                        <div> <Link href="/inspection" >Inspection</Link></div>
                    </>
                )
            }
        </div>
        {
            search && <div className={styles.search}>
                <input
                    type="text"
                    placeholder="Search..."
                    onBlur={(e) => router.push("/all?filter=" + e.target.value)}
                />
            </div>
        }
        <div className={styles.profile}>
            <Image className={styles.profileImage} src={user?.photoURL || profile.src} alt="" 
                width={24} height={24} onClick={() => {user ? handleGoogleSignOut() : handleGoogleSignIn()}}/>
        </div>
    </div>);
}

export default Navbar;
